# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-26 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('published_datetime', models.DateTimeField()),
                ('thumbnail_url', models.URLField()),
                ('channel_id', models.CharField(max_length=255)),
            ],
        ),
    ]
