# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-26 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_video_video_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-publishedDateTime',)},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='thumbnail_url',
            new_name='thumbnailsUrls',
        ),
        migrations.RemoveField(
            model_name='video',
            name='published_datetime',
        ),
        migrations.AddField(
            model_name='video',
            name='channel_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='publishedDateTime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='channel_id',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
